/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.achess.test;

import com.achess.UI.LineNumber;
import com.achess.backend.Automaton;
import com.achess.backend.Token;
import com.achess.backend.WordAutomaton;
import java.awt.Color;
import java.awt.Component;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter;

/**
 *
 * @author achess
 */
public class TestFrame extends javax.swing.JFrame {

    /**
     * Creates new form TestFrame
     */
    public TestFrame() {        
        initComponents();        
        LineNumber nl = new LineNumber(textSpace);
        jScrollPane1.setRowHeaderView(nl);
        LineNumber n2 = new LineNumber(textFound);
        jScrollPane2.setRowHeaderView(n2);
        jScrollPane2.setVisible(false);
        textFound.setEditable(false);
        jButton1.setVisible(false);    
        addTable();
    }
    
    private void addTable(){        
    }
    
    private void updateRowHeights(JTable table)
{
    for (int row = 0; row < table.getRowCount(); row++)
    {
        int rowHeight = table.getRowHeight();

        for (int column = 0; column < table.getColumnCount(); column++)
        {
            Component comp = table.prepareRenderer(table.getCellRenderer(row, column), row, column);
            rowHeight = Math.max(rowHeight, comp.getPreferredSize().height);
        }

        table.setRowHeight(row, rowHeight);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonAnalize = new javax.swing.JButton();
        textFWord = new javax.swing.JTextField();
        buttonSearch = new javax.swing.JButton();
        labelCords = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textSpace = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textFound = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(80, 77, 81));

        buttonAnalize.setText("Analizar");
        buttonAnalize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAnalizeActionPerformed(evt);
            }
        });

        buttonSearch.setText("Buscar");
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });

        labelCords.setText("Ln: 1 Col: 1");

        textSpace.setBackground(new java.awt.Color(46, 41, 46));
        textSpace.setColumns(20);
        textSpace.setFont(new java.awt.Font("Liberation Mono", 0, 14)); // NOI18N
        textSpace.setForeground(new java.awt.Color(255, 255, 255));
        textSpace.setRows(5);
        textSpace.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                textSpaceCaretUpdate(evt);
            }
        });
        textSpace.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textSpaceFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(textSpace);

        textFound.setBackground(new java.awt.Color(46, 41, 46));
        textFound.setColumns(20);
        textFound.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        textFound.setRows(5);
        jScrollPane2.setViewportView(textFound);

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setText("X");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTable1.setBackground(new java.awt.Color(46, 41, 46));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(41, 46, 41));
        jTable1.setShowHorizontalLines(true);
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelCords)
                            .addComponent(buttonSearch))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonAnalize)
                            .addComponent(textFWord, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCords)
                    .addComponent(buttonAnalize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSearch))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAnalizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAnalizeActionPerformed
        // TODO add your handling code here:
        String text = textSpace.getText();
        Automaton.getAutomaton().analize(text);
        DefaultTableModel model = new DefaultTableModel();              
        model.addColumn("Nombre");        
        model.addColumn("Lexeme");
        model.addColumn("Posición");          
        model.addColumn("Movimientos");
        this.jTable1.setModel(model);        
        this.jTable1.setEnabled(false);        
        for(Token tk : Automaton.getAutomaton().getTokens()){                        
            String cords = "Fila: "+ tk.getRow() + " Columna: " + tk.getColumn();
            Object[] data = {tk.getType().getType(), tk.getLexeme(), cords, tk.getMovements()};
            System.out.println(tk.getMovements());
            model.addRow(data);
        }
        System.out.println("Errores-------------------------------");
        for(Token tk : Automaton.getAutomaton().getErrors()){
            System.out.println(tk.getMovements());                        
        }
        this.updateRowHeights(this.jTable1);
        //JDialog dia = new NewJDialog(this, true);
        //dia.setLocationRelativeTo(null);
        //dia.setVisible(true);        
    }//GEN-LAST:event_buttonAnalizeActionPerformed

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        // TODO add your handling code here:       
        jScrollPane2.setVisible(true);
        jButton1.setVisible(true);
        SwingUtilities.updateComponentTreeUI(this);
        textFound.getHighlighter().removeAllHighlights();
        Highlighter hilit;
        Highlighter.HighlightPainter painter;
        hilit = new DefaultHighlighter();        
        painter = new DefaultHighlighter.DefaultHighlightPainter(Color.CYAN);
        textFound.setHighlighter(hilit);
        String text = textSpace.getText();
        String word = textFWord.getText();
        textFound.setText(text);
        WordAutomaton autW = new WordAutomaton(word);
        autW.analize(text);
        System.out.println("---------------------");
        for(Token tk : autW.getWords()){
            try {            
                hilit.addHighlight(tk.getBegin(),tk.getEnd() ,painter);
                textFound.setCaretPosition(tk.getEnd());
            } catch (BadLocationException ex) {
                ex.printStackTrace(System.out);
            }
        }               
    }//GEN-LAST:event_buttonSearchActionPerformed

    private void textSpaceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textSpaceFocusGained
        // TODO add your handling code here:
        textSpace.getHighlighter().removeAllHighlights();
    }//GEN-LAST:event_textSpaceFocusGained

    private void textSpaceCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_textSpaceCaretUpdate
        // TODO add your handling code here:
        try{
            JTextArea txt = this.textSpace;
            int caretOffset = txt.getCaretPosition();
            int lineNumber = txt.getLineOfOffset(caretOffset);                    
            int col = caretOffset - txt.getLineStartOffset(lineNumber) + 1;
            lineNumber+=1;            
            labelCords.setText("Ln:" + lineNumber +" Col: " + col);            
        }
        catch(Exception ex){
            ex.printStackTrace(System.out);
        }
    }//GEN-LAST:event_textSpaceCaretUpdate

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.jScrollPane2.setVisible(false);
        this.jButton1.setVisible(false);
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAnalize;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelCords;
    private javax.swing.JTextField textFWord;
    private javax.swing.JTextArea textFound;
    private javax.swing.JTextArea textSpace;
    // End of variables declaration//GEN-END:variables
}
